// flow-typed signature: 633a381c1afd4d3163947149a1af3596
// flow-typed version: <<STUB>>/expo-optimize_v0.1.46/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-optimize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-optimize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-optimize/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-optimize/build/index' {
  declare module.exports: $Exports<'expo-optimize/build'>;
}
declare module 'expo-optimize/build/index.js' {
  declare module.exports: $Exports<'expo-optimize/build'>;
}
