// flow-typed signature: 5dc4958e831d6789d8ebbbcf4eaf7fdb
// flow-typed version: <<STUB>>/expo-haptics_v~8.3.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-haptics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-haptics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-haptics/build/ExpoHaptics' {
  declare module.exports: any;
}

declare module 'expo-haptics/build/ExpoHaptics.web' {
  declare module.exports: any;
}

declare module 'expo-haptics/build/Haptics' {
  declare module.exports: any;
}

declare module 'expo-haptics/build/Haptics.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-haptics/build/ExpoHaptics.js' {
  declare module.exports: $Exports<'expo-haptics/build/ExpoHaptics'>;
}
declare module 'expo-haptics/build/ExpoHaptics.web.js' {
  declare module.exports: $Exports<'expo-haptics/build/ExpoHaptics.web'>;
}
declare module 'expo-haptics/build/Haptics.js' {
  declare module.exports: $Exports<'expo-haptics/build/Haptics'>;
}
declare module 'expo-haptics/build/Haptics.types.js' {
  declare module.exports: $Exports<'expo-haptics/build/Haptics.types'>;
}
