// flow-typed signature: 5141be0b31d1d39af2400e0b5f1d4151
// flow-typed version: <<STUB>>/expo-ads-admob_v~8.3.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-ads-admob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-ads-admob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-ads-admob/build/AdMob' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobBanner' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobBanner.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobInterstitial' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobInterstitial.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobRewarded' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/AdMobRewarded.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMob' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMob.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager.web' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/PublisherBanner' {
  declare module.exports: any;
}

declare module 'expo-ads-admob/build/PublisherBanner.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-ads-admob/build/AdMob.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMob'>;
}
declare module 'expo-ads-admob/build/AdMobBanner.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobBanner'>;
}
declare module 'expo-ads-admob/build/AdMobBanner.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobBanner.web'>;
}
declare module 'expo-ads-admob/build/AdMobInterstitial.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobInterstitial'>;
}
declare module 'expo-ads-admob/build/AdMobInterstitial.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobInterstitial.web'>;
}
declare module 'expo-ads-admob/build/AdMobRewarded.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobRewarded'>;
}
declare module 'expo-ads-admob/build/AdMobRewarded.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/AdMobRewarded.web'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMob.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMob'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMob.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMob.web'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMobInterstitialManager.web'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager'>;
}
declare module 'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/ExpoAdsAdMobRewardedVideoAdManager.web'>;
}
declare module 'expo-ads-admob/build/index' {
  declare module.exports: $Exports<'expo-ads-admob/build'>;
}
declare module 'expo-ads-admob/build/index.js' {
  declare module.exports: $Exports<'expo-ads-admob/build'>;
}
declare module 'expo-ads-admob/build/PublisherBanner.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/PublisherBanner'>;
}
declare module 'expo-ads-admob/build/PublisherBanner.web.js' {
  declare module.exports: $Exports<'expo-ads-admob/build/PublisherBanner.web'>;
}
