// flow-typed signature: 9f4ddc4f89ed06047c082424eb6e8468
// flow-typed version: <<STUB>>/expo-linking_v1.0.4/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-linking'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-linking' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-linking/build/ExpoLinking' {
  declare module.exports: any;
}

declare module 'expo-linking/build/ExpoLinking.web' {
  declare module.exports: any;
}

declare module 'expo-linking/build/Linking' {
  declare module.exports: any;
}

declare module 'expo-linking/build/Linking.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-linking/build/ExpoLinking.js' {
  declare module.exports: $Exports<'expo-linking/build/ExpoLinking'>;
}
declare module 'expo-linking/build/ExpoLinking.web.js' {
  declare module.exports: $Exports<'expo-linking/build/ExpoLinking.web'>;
}
declare module 'expo-linking/build/Linking.js' {
  declare module.exports: $Exports<'expo-linking/build/Linking'>;
}
declare module 'expo-linking/build/Linking.types.js' {
  declare module.exports: $Exports<'expo-linking/build/Linking.types'>;
}
