// flow-typed signature: 8621cfa22940e88f848c7333ae5dec02
// flow-typed version: <<STUB>>/expo-constants_v~9.2.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-constants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-constants/build/Constants' {
  declare module.exports: any;
}

declare module 'expo-constants/build/Constants.types' {
  declare module.exports: any;
}

declare module 'expo-constants/build/ExponentConstants' {
  declare module.exports: any;
}

declare module 'expo-constants/build/ExponentConstants.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-constants/build/Constants.js' {
  declare module.exports: $Exports<'expo-constants/build/Constants'>;
}
declare module 'expo-constants/build/Constants.types.js' {
  declare module.exports: $Exports<'expo-constants/build/Constants.types'>;
}
declare module 'expo-constants/build/ExponentConstants.js' {
  declare module.exports: $Exports<'expo-constants/build/ExponentConstants'>;
}
declare module 'expo-constants/build/ExponentConstants.web.js' {
  declare module.exports: $Exports<'expo-constants/build/ExponentConstants.web'>;
}
