// flow-typed signature: e418232fe89d921e4ccb40af38b1847e
// flow-typed version: <<STUB>>/expo-screen-orientation_v~2.0.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-screen-orientation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-screen-orientation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-screen-orientation/build/ExpoScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo-screen-orientation/build/ExpoScreenOrientation.web' {
  declare module.exports: any;
}

declare module 'expo-screen-orientation/build/ScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo-screen-orientation/build/ScreenOrientation.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-screen-orientation/build/ExpoScreenOrientation.js' {
  declare module.exports: $Exports<'expo-screen-orientation/build/ExpoScreenOrientation'>;
}
declare module 'expo-screen-orientation/build/ExpoScreenOrientation.web.js' {
  declare module.exports: $Exports<'expo-screen-orientation/build/ExpoScreenOrientation.web'>;
}
declare module 'expo-screen-orientation/build/ScreenOrientation.js' {
  declare module.exports: $Exports<'expo-screen-orientation/build/ScreenOrientation'>;
}
declare module 'expo-screen-orientation/build/ScreenOrientation.types.js' {
  declare module.exports: $Exports<'expo-screen-orientation/build/ScreenOrientation.types'>;
}
