// flow-typed signature: 52e2878bb65c2b2f9cc7adf7d93a0d0d
// flow-typed version: <<STUB>>/expo-localization_v~9.0.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-localization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-localization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-localization/build/ExpoLocalization' {
  declare module.exports: any;
}

declare module 'expo-localization/build/ExpoLocalization.native' {
  declare module.exports: any;
}

declare module 'expo-localization/build/Localization' {
  declare module.exports: any;
}

declare module 'expo-localization/build/Localization.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-localization/build/ExpoLocalization.js' {
  declare module.exports: $Exports<'expo-localization/build/ExpoLocalization'>;
}
declare module 'expo-localization/build/ExpoLocalization.native.js' {
  declare module.exports: $Exports<'expo-localization/build/ExpoLocalization.native'>;
}
declare module 'expo-localization/build/Localization.js' {
  declare module.exports: $Exports<'expo-localization/build/Localization'>;
}
declare module 'expo-localization/build/Localization.types.js' {
  declare module.exports: $Exports<'expo-localization/build/Localization.types'>;
}
