// flow-typed signature: 5ff37f96a5ab53aba5f6121a7519c948
// flow-typed version: <<STUB>>/expo-store-review_v~2.2.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-store-review'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-store-review' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-store-review/build/ExpoStoreReview' {
  declare module.exports: any;
}

declare module 'expo-store-review/build/ExpoStoreReview.native' {
  declare module.exports: any;
}

declare module 'expo-store-review/build/StoreReview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-store-review/build/ExpoStoreReview.js' {
  declare module.exports: $Exports<'expo-store-review/build/ExpoStoreReview'>;
}
declare module 'expo-store-review/build/ExpoStoreReview.native.js' {
  declare module.exports: $Exports<'expo-store-review/build/ExpoStoreReview.native'>;
}
declare module 'expo-store-review/build/StoreReview.js' {
  declare module.exports: $Exports<'expo-store-review/build/StoreReview'>;
}
