// flow-typed signature: 72beb8f767a6d298a98275d141d56157
// flow-typed version: <<STUB>>/expo-notifications_v~0.7.2/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-notifications/build/BadgeModule' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/BadgeModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/BadgeModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/BadgeModule.web' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/cancelAllScheduledNotificationsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/cancelScheduledNotificationAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/deleteNotificationCategoryAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/deleteNotificationChannelAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/deleteNotificationChannelAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/deleteNotificationChannelGroupAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/deleteNotificationChannelGroupAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/dismissAllNotificationsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/dismissNotificationAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getAllScheduledNotificationsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getBadgeCountAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getDevicePushTokenAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getDevicePushTokenAsync.web' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getExpoPushTokenAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationCategoriesAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelGroupAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelGroupAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelGroupsAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelGroupsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelsAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getNotificationChannelsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/getPresentedNotificationsAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/InstallationIdProvider' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/InstallationIdProvider.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/InstallationIdProvider.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/InstallationIdProvider.web' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationCategoriesModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationCategoriesModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationCategoriesModule.web' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelGroupManager' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelGroupManager.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelGroupManager.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelManager' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelManager.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationChannelManager.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPermissions' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPermissions.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPermissionsModule' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPermissionsModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPermissionsModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPresenterModule' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPresenterModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationPresenterModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/Notifications.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationScheduler' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationScheduler.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationScheduler.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsEmitter' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsEmitterModule' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsEmitterModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsEmitterModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsHandler' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsHandlerModule' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsHandlerModule.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/NotificationsHandlerModule.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/presentNotificationAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/PushTokenManager' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/PushTokenManager.native' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/PushTokenManager.types' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/scheduleNotificationAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setBadgeCountAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setNotificationCategoryAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setNotificationChannelAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setNotificationChannelAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setNotificationChannelGroupAsync.android' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/setNotificationChannelGroupAsync' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/TokenEmitter' {
  declare module.exports: any;
}

declare module 'expo-notifications/build/Tokens.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-notifications/build/BadgeModule.js' {
  declare module.exports: $Exports<'expo-notifications/build/BadgeModule'>;
}
declare module 'expo-notifications/build/BadgeModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/BadgeModule.native'>;
}
declare module 'expo-notifications/build/BadgeModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/BadgeModule.types'>;
}
declare module 'expo-notifications/build/BadgeModule.web.js' {
  declare module.exports: $Exports<'expo-notifications/build/BadgeModule.web'>;
}
declare module 'expo-notifications/build/cancelAllScheduledNotificationsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/cancelAllScheduledNotificationsAsync'>;
}
declare module 'expo-notifications/build/cancelScheduledNotificationAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/cancelScheduledNotificationAsync'>;
}
declare module 'expo-notifications/build/deleteNotificationCategoryAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/deleteNotificationCategoryAsync'>;
}
declare module 'expo-notifications/build/deleteNotificationChannelAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/deleteNotificationChannelAsync.android'>;
}
declare module 'expo-notifications/build/deleteNotificationChannelAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/deleteNotificationChannelAsync'>;
}
declare module 'expo-notifications/build/deleteNotificationChannelGroupAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/deleteNotificationChannelGroupAsync.android'>;
}
declare module 'expo-notifications/build/deleteNotificationChannelGroupAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/deleteNotificationChannelGroupAsync'>;
}
declare module 'expo-notifications/build/dismissAllNotificationsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/dismissAllNotificationsAsync'>;
}
declare module 'expo-notifications/build/dismissNotificationAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/dismissNotificationAsync'>;
}
declare module 'expo-notifications/build/getAllScheduledNotificationsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getAllScheduledNotificationsAsync'>;
}
declare module 'expo-notifications/build/getBadgeCountAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getBadgeCountAsync'>;
}
declare module 'expo-notifications/build/getDevicePushTokenAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getDevicePushTokenAsync'>;
}
declare module 'expo-notifications/build/getDevicePushTokenAsync.web.js' {
  declare module.exports: $Exports<'expo-notifications/build/getDevicePushTokenAsync.web'>;
}
declare module 'expo-notifications/build/getExpoPushTokenAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getExpoPushTokenAsync'>;
}
declare module 'expo-notifications/build/getNotificationCategoriesAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationCategoriesAsync'>;
}
declare module 'expo-notifications/build/getNotificationChannelAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelAsync.android'>;
}
declare module 'expo-notifications/build/getNotificationChannelAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelAsync'>;
}
declare module 'expo-notifications/build/getNotificationChannelGroupAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelGroupAsync.android'>;
}
declare module 'expo-notifications/build/getNotificationChannelGroupAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelGroupAsync'>;
}
declare module 'expo-notifications/build/getNotificationChannelGroupsAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelGroupsAsync.android'>;
}
declare module 'expo-notifications/build/getNotificationChannelGroupsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelGroupsAsync'>;
}
declare module 'expo-notifications/build/getNotificationChannelsAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelsAsync.android'>;
}
declare module 'expo-notifications/build/getNotificationChannelsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getNotificationChannelsAsync'>;
}
declare module 'expo-notifications/build/getPresentedNotificationsAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/getPresentedNotificationsAsync'>;
}
declare module 'expo-notifications/build/index' {
  declare module.exports: $Exports<'expo-notifications/build'>;
}
declare module 'expo-notifications/build/index.js' {
  declare module.exports: $Exports<'expo-notifications/build'>;
}
declare module 'expo-notifications/build/InstallationIdProvider.js' {
  declare module.exports: $Exports<'expo-notifications/build/InstallationIdProvider'>;
}
declare module 'expo-notifications/build/InstallationIdProvider.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/InstallationIdProvider.native'>;
}
declare module 'expo-notifications/build/InstallationIdProvider.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/InstallationIdProvider.types'>;
}
declare module 'expo-notifications/build/InstallationIdProvider.web.js' {
  declare module.exports: $Exports<'expo-notifications/build/InstallationIdProvider.web'>;
}
declare module 'expo-notifications/build/NotificationCategoriesModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationCategoriesModule.native'>;
}
declare module 'expo-notifications/build/NotificationCategoriesModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationCategoriesModule.types'>;
}
declare module 'expo-notifications/build/NotificationCategoriesModule.web.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationCategoriesModule.web'>;
}
declare module 'expo-notifications/build/NotificationChannelGroupManager.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelGroupManager'>;
}
declare module 'expo-notifications/build/NotificationChannelGroupManager.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelGroupManager.native'>;
}
declare module 'expo-notifications/build/NotificationChannelGroupManager.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelGroupManager.types'>;
}
declare module 'expo-notifications/build/NotificationChannelManager.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelManager'>;
}
declare module 'expo-notifications/build/NotificationChannelManager.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelManager.native'>;
}
declare module 'expo-notifications/build/NotificationChannelManager.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationChannelManager.types'>;
}
declare module 'expo-notifications/build/NotificationPermissions.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPermissions'>;
}
declare module 'expo-notifications/build/NotificationPermissions.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPermissions.types'>;
}
declare module 'expo-notifications/build/NotificationPermissionsModule.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPermissionsModule'>;
}
declare module 'expo-notifications/build/NotificationPermissionsModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPermissionsModule.native'>;
}
declare module 'expo-notifications/build/NotificationPermissionsModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPermissionsModule.types'>;
}
declare module 'expo-notifications/build/NotificationPresenterModule.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPresenterModule'>;
}
declare module 'expo-notifications/build/NotificationPresenterModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPresenterModule.native'>;
}
declare module 'expo-notifications/build/NotificationPresenterModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationPresenterModule.types'>;
}
declare module 'expo-notifications/build/Notifications.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/Notifications.types'>;
}
declare module 'expo-notifications/build/NotificationScheduler.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationScheduler'>;
}
declare module 'expo-notifications/build/NotificationScheduler.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationScheduler.native'>;
}
declare module 'expo-notifications/build/NotificationScheduler.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationScheduler.types'>;
}
declare module 'expo-notifications/build/NotificationsEmitter.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsEmitter'>;
}
declare module 'expo-notifications/build/NotificationsEmitterModule.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsEmitterModule'>;
}
declare module 'expo-notifications/build/NotificationsEmitterModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsEmitterModule.native'>;
}
declare module 'expo-notifications/build/NotificationsEmitterModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsEmitterModule.types'>;
}
declare module 'expo-notifications/build/NotificationsHandler.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsHandler'>;
}
declare module 'expo-notifications/build/NotificationsHandlerModule.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsHandlerModule'>;
}
declare module 'expo-notifications/build/NotificationsHandlerModule.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsHandlerModule.native'>;
}
declare module 'expo-notifications/build/NotificationsHandlerModule.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/NotificationsHandlerModule.types'>;
}
declare module 'expo-notifications/build/presentNotificationAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/presentNotificationAsync'>;
}
declare module 'expo-notifications/build/PushTokenManager.js' {
  declare module.exports: $Exports<'expo-notifications/build/PushTokenManager'>;
}
declare module 'expo-notifications/build/PushTokenManager.native.js' {
  declare module.exports: $Exports<'expo-notifications/build/PushTokenManager.native'>;
}
declare module 'expo-notifications/build/PushTokenManager.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/PushTokenManager.types'>;
}
declare module 'expo-notifications/build/scheduleNotificationAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/scheduleNotificationAsync'>;
}
declare module 'expo-notifications/build/setBadgeCountAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/setBadgeCountAsync'>;
}
declare module 'expo-notifications/build/setNotificationCategoryAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/setNotificationCategoryAsync'>;
}
declare module 'expo-notifications/build/setNotificationChannelAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/setNotificationChannelAsync.android'>;
}
declare module 'expo-notifications/build/setNotificationChannelAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/setNotificationChannelAsync'>;
}
declare module 'expo-notifications/build/setNotificationChannelGroupAsync.android.js' {
  declare module.exports: $Exports<'expo-notifications/build/setNotificationChannelGroupAsync.android'>;
}
declare module 'expo-notifications/build/setNotificationChannelGroupAsync.js' {
  declare module.exports: $Exports<'expo-notifications/build/setNotificationChannelGroupAsync'>;
}
declare module 'expo-notifications/build/TokenEmitter.js' {
  declare module.exports: $Exports<'expo-notifications/build/TokenEmitter'>;
}
declare module 'expo-notifications/build/Tokens.types.js' {
  declare module.exports: $Exports<'expo-notifications/build/Tokens.types'>;
}
