// flow-typed signature: 1adc0f8ca57644dce05644e37a6bbdea
// flow-typed version: <<STUB>>/expo-cli_v3.28.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-cli/bin/expo' {
  declare module.exports: any;
}

declare module 'expo-cli/build/accounts' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/authenticate' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/createManagers' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/distributionCert' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/ensureAppExists' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/fastlane' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/keychain' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/provisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/provisioningProfileAdhoc' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/pushKey' {
  declare module.exports: any;
}

declare module 'expo-cli/build/appleApi/setup' {
  declare module.exports: any;
}

declare module 'expo-cli/build/askUser' {
  declare module.exports: any;
}

declare module 'expo-cli/build/CommandError' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/apply' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/apply/configureAndroidProjectAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/apply/configureIOSProjectAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/AndroidBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BaseBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BaseBuilder.types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/BuildError' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/constants' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/ios/IOSBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/ios/utils/image' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/build/utils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/bundle-assets' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client/clientBuildApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client/generateBundleIdentifier' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/client' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/customize' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/diagnostics' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/doctor' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/action' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/builders/AndroidBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/builders/iOSBuilder' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/metadata' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/templates/gradleContent' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/build/utils/ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/constants' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/credentialsSync/action' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/init/action' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/status/action' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/analytics' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/createBuilderContext' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/createCommandContextAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/android' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/getConfigurationOptions' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/isExpoUpdatesInstalled' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/git' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eas-build/utils/misc' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject/ConfigValidation' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject/Eject' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/eject/LegacyEject' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/export' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch/android' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/fetch/ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/configureModule' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/fetchTemplate' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/generateModuleAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/ModuleConfiguration' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/generate-module/promptQuestionsAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/init' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/install' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/login' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/logout' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/prepare-detached-build' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish-info' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish-modify' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/publish' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/push-creds' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/register' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/send' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/start' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/start/TerminalUI' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upgrade' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/BaseUploader' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/IOSUploader' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidPackageSource' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmissionConfig' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitCommand' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitter' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/ServiceAccountSource' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/android/types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveFileSource' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveTypeSource' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/archive-source' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/SubmissionService' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/SubmissionService.types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/types' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/utils/config' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/utils/errors' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/utils/files' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/utils/logs' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/submission-service/utils/travelingFastlane' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/upload/utils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/url' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/cli-table' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/ClientUpgradeUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/CreateApp' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/EditorUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/GitIgnore' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/logConfigWarnings' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/maybeBailOnGitStatusAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/progress' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/ProjectUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/promise' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/PublishUtils' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/Tar' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/TerminalLink' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/utils/url' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/webhooks' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commands/whoami' {
  declare module.exports: any;
}

declare module 'expo-cli/build/commonOptions' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/actions/list' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/actions/promptForCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/api/AndroidApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/api/AndroidApiV2Wrapper' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/api/IosApi' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/api/IosApiV2Wrapper' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/context' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/credentialsJson/read' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/credentialsJson/update' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/provider/AndroidCredentialsProvider' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/provider' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/provider/iOSCredentialsProvider' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/provider/provider' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/route' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/test-fixtures/mock-base64-data' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/test-fixtures/mocks-android' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/test-fixtures/mocks-constants' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/test-fixtures/mocks-context' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/test-fixtures/mocks-ios' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/utils/provisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/AndroidCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/AndroidKeystore' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/AndroidPushCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosAppCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosDistCert' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosProvisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/IosPushCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/Select' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupAndroidKeystore' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosBuildCredentials' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosDist' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosProvisioningProfile' {
  declare module.exports: any;
}

declare module 'expo-cli/build/credentials/views/SetupIosPush' {
  declare module.exports: any;
}

declare module 'expo-cli/build/easJson' {
  declare module.exports: any;
}

declare module 'expo-cli/build/exit' {
  declare module.exports: any;
}

declare module 'expo-cli/build/exp' {
  declare module.exports: any;
}

declare module 'expo-cli/build/git' {
  declare module.exports: any;
}

declare module 'expo-cli/build/log' {
  declare module.exports: any;
}

declare module 'expo-cli/build/printRunInstructionsAsync' {
  declare module.exports: any;
}

declare module 'expo-cli/build/projects' {
  declare module.exports: any;
}

declare module 'expo-cli/build/prompt' {
  declare module.exports: any;
}

declare module 'expo-cli/build/prompts' {
  declare module.exports: any;
}

declare module 'expo-cli/build/sendTo' {
  declare module.exports: any;
}

declare module 'expo-cli/build/update' {
  declare module.exports: any;
}

declare module 'expo-cli/build/uploads' {
  declare module.exports: any;
}

declare module 'expo-cli/build/urlOpts' {
  declare module.exports: any;
}

declare module 'expo-cli/build/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-cli/bin/expo.js' {
  declare module.exports: $Exports<'expo-cli/bin/expo'>;
}
declare module 'expo-cli/build/accounts.js' {
  declare module.exports: $Exports<'expo-cli/build/accounts'>;
}
declare module 'expo-cli/build/appleApi/authenticate.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/authenticate'>;
}
declare module 'expo-cli/build/appleApi/createManagers.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/createManagers'>;
}
declare module 'expo-cli/build/appleApi/distributionCert.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/distributionCert'>;
}
declare module 'expo-cli/build/appleApi/ensureAppExists.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/ensureAppExists'>;
}
declare module 'expo-cli/build/appleApi/fastlane.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/fastlane'>;
}
declare module 'expo-cli/build/appleApi/index' {
  declare module.exports: $Exports<'expo-cli/build/appleApi'>;
}
declare module 'expo-cli/build/appleApi/index.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi'>;
}
declare module 'expo-cli/build/appleApi/keychain.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/keychain'>;
}
declare module 'expo-cli/build/appleApi/provisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/provisioningProfile'>;
}
declare module 'expo-cli/build/appleApi/provisioningProfileAdhoc.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/provisioningProfileAdhoc'>;
}
declare module 'expo-cli/build/appleApi/pushKey.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/pushKey'>;
}
declare module 'expo-cli/build/appleApi/setup.js' {
  declare module.exports: $Exports<'expo-cli/build/appleApi/setup'>;
}
declare module 'expo-cli/build/askUser.js' {
  declare module.exports: $Exports<'expo-cli/build/askUser'>;
}
declare module 'expo-cli/build/CommandError.js' {
  declare module.exports: $Exports<'expo-cli/build/CommandError'>;
}
declare module 'expo-cli/build/commands/apply.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/apply'>;
}
declare module 'expo-cli/build/commands/apply/configureAndroidProjectAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/apply/configureAndroidProjectAsync'>;
}
declare module 'expo-cli/build/commands/apply/configureIOSProjectAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/apply/configureIOSProjectAsync'>;
}
declare module 'expo-cli/build/commands/build/AndroidBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/AndroidBuilder'>;
}
declare module 'expo-cli/build/commands/build/BaseBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BaseBuilder'>;
}
declare module 'expo-cli/build/commands/build/BaseBuilder.types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BaseBuilder.types'>;
}
declare module 'expo-cli/build/commands/build/BuildError.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/BuildError'>;
}
declare module 'expo-cli/build/commands/build/constants.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/constants'>;
}
declare module 'expo-cli/build/commands/build/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/build'>;
}
declare module 'expo-cli/build/commands/build/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build'>;
}
declare module 'expo-cli/build/commands/build/ios/IOSBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/ios/IOSBuilder'>;
}
declare module 'expo-cli/build/commands/build/ios/utils/image.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/ios/utils/image'>;
}
declare module 'expo-cli/build/commands/build/utils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/build/utils'>;
}
declare module 'expo-cli/build/commands/bundle-assets.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/bundle-assets'>;
}
declare module 'expo-cli/build/commands/client/clientBuildApi.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client/clientBuildApi'>;
}
declare module 'expo-cli/build/commands/client/generateBundleIdentifier.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client/generateBundleIdentifier'>;
}
declare module 'expo-cli/build/commands/client/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/client'>;
}
declare module 'expo-cli/build/commands/client/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/client'>;
}
declare module 'expo-cli/build/commands/credentials.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/credentials'>;
}
declare module 'expo-cli/build/commands/customize.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/customize'>;
}
declare module 'expo-cli/build/commands/diagnostics.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/diagnostics'>;
}
declare module 'expo-cli/build/commands/doctor.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/doctor'>;
}
declare module 'expo-cli/build/commands/eas-build/build/action.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/action'>;
}
declare module 'expo-cli/build/commands/eas-build/build/builders/AndroidBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/builders/AndroidBuilder'>;
}
declare module 'expo-cli/build/commands/eas-build/build/builders/iOSBuilder.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/builders/iOSBuilder'>;
}
declare module 'expo-cli/build/commands/eas-build/build/credentials.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/credentials'>;
}
declare module 'expo-cli/build/commands/eas-build/build/metadata.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/metadata'>;
}
declare module 'expo-cli/build/commands/eas-build/build/templates/gradleContent.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/templates/gradleContent'>;
}
declare module 'expo-cli/build/commands/eas-build/build/utils/ios.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/build/utils/ios'>;
}
declare module 'expo-cli/build/commands/eas-build/constants.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/constants'>;
}
declare module 'expo-cli/build/commands/eas-build/credentialsSync/action.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/credentialsSync/action'>;
}
declare module 'expo-cli/build/commands/eas-build/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build'>;
}
declare module 'expo-cli/build/commands/eas-build/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build'>;
}
declare module 'expo-cli/build/commands/eas-build/init/action.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/init/action'>;
}
declare module 'expo-cli/build/commands/eas-build/status/action.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/status/action'>;
}
declare module 'expo-cli/build/commands/eas-build/types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/types'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/analytics.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/analytics'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/createBuilderContext.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/createBuilderContext'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/createCommandContextAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/createCommandContextAsync'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/android.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates/android'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/getConfigurationOptions.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates/getConfigurationOptions'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/ios.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates/ios'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/expoUpdates/isExpoUpdatesInstalled.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/expoUpdates/isExpoUpdatesInstalled'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/git.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/git'>;
}
declare module 'expo-cli/build/commands/eas-build/utils/misc.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eas-build/utils/misc'>;
}
declare module 'expo-cli/build/commands/eject.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject'>;
}
declare module 'expo-cli/build/commands/eject/ConfigValidation.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject/ConfigValidation'>;
}
declare module 'expo-cli/build/commands/eject/Eject.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject/Eject'>;
}
declare module 'expo-cli/build/commands/eject/LegacyEject.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/eject/LegacyEject'>;
}
declare module 'expo-cli/build/commands/export.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/export'>;
}
declare module 'expo-cli/build/commands/fetch/android.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch/android'>;
}
declare module 'expo-cli/build/commands/fetch/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch'>;
}
declare module 'expo-cli/build/commands/fetch/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch'>;
}
declare module 'expo-cli/build/commands/fetch/ios.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/fetch/ios'>;
}
declare module 'expo-cli/build/commands/generate-module.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module'>;
}
declare module 'expo-cli/build/commands/generate-module/configureModule.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/configureModule'>;
}
declare module 'expo-cli/build/commands/generate-module/fetchTemplate.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/fetchTemplate'>;
}
declare module 'expo-cli/build/commands/generate-module/generateModuleAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/generateModuleAsync'>;
}
declare module 'expo-cli/build/commands/generate-module/ModuleConfiguration.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/ModuleConfiguration'>;
}
declare module 'expo-cli/build/commands/generate-module/promptQuestionsAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/generate-module/promptQuestionsAsync'>;
}
declare module 'expo-cli/build/commands/index' {
  declare module.exports: $Exports<'expo-cli/build/commands'>;
}
declare module 'expo-cli/build/commands/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands'>;
}
declare module 'expo-cli/build/commands/init.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/init'>;
}
declare module 'expo-cli/build/commands/install.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/install'>;
}
declare module 'expo-cli/build/commands/login.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/login'>;
}
declare module 'expo-cli/build/commands/logout.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/logout'>;
}
declare module 'expo-cli/build/commands/prepare-detached-build.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/prepare-detached-build'>;
}
declare module 'expo-cli/build/commands/publish-info.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish-info'>;
}
declare module 'expo-cli/build/commands/publish-modify.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish-modify'>;
}
declare module 'expo-cli/build/commands/publish.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/publish'>;
}
declare module 'expo-cli/build/commands/push-creds.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/push-creds'>;
}
declare module 'expo-cli/build/commands/register.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/register'>;
}
declare module 'expo-cli/build/commands/send.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/send'>;
}
declare module 'expo-cli/build/commands/start.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/start'>;
}
declare module 'expo-cli/build/commands/start/TerminalUI.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/start/TerminalUI'>;
}
declare module 'expo-cli/build/commands/upgrade.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upgrade'>;
}
declare module 'expo-cli/build/commands/upload.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload'>;
}
declare module 'expo-cli/build/commands/upload/BaseUploader.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/BaseUploader'>;
}
declare module 'expo-cli/build/commands/upload/IOSUploader.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/IOSUploader'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidPackageSource.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/AndroidPackageSource'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmissionConfig.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/AndroidSubmissionConfig'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitCommand.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitCommand'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitter.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/AndroidSubmitter'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/ServiceAccountSource.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/ServiceAccountSource'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/android/types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/android/types'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveFileSource.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveFileSource'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveTypeSource.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/archive-source/ArchiveTypeSource'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/archive-source/index' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/archive-source'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/archive-source/index.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/archive-source'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/SubmissionService.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/SubmissionService'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/SubmissionService.types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/SubmissionService.types'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/types.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/types'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/utils/config.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/utils/config'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/utils/errors.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/utils/errors'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/utils/files.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/utils/files'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/utils/logs.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/utils/logs'>;
}
declare module 'expo-cli/build/commands/upload/submission-service/utils/travelingFastlane.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/submission-service/utils/travelingFastlane'>;
}
declare module 'expo-cli/build/commands/upload/utils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/upload/utils'>;
}
declare module 'expo-cli/build/commands/url.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/url'>;
}
declare module 'expo-cli/build/commands/utils/cli-table.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/cli-table'>;
}
declare module 'expo-cli/build/commands/utils/ClientUpgradeUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/ClientUpgradeUtils'>;
}
declare module 'expo-cli/build/commands/utils/CreateApp.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/CreateApp'>;
}
declare module 'expo-cli/build/commands/utils/EditorUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/EditorUtils'>;
}
declare module 'expo-cli/build/commands/utils/GitIgnore.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/GitIgnore'>;
}
declare module 'expo-cli/build/commands/utils/logConfigWarnings.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/logConfigWarnings'>;
}
declare module 'expo-cli/build/commands/utils/maybeBailOnGitStatusAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/maybeBailOnGitStatusAsync'>;
}
declare module 'expo-cli/build/commands/utils/progress.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/progress'>;
}
declare module 'expo-cli/build/commands/utils/ProjectUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/ProjectUtils'>;
}
declare module 'expo-cli/build/commands/utils/promise.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/promise'>;
}
declare module 'expo-cli/build/commands/utils/PublishUtils.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/PublishUtils'>;
}
declare module 'expo-cli/build/commands/utils/Tar.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/Tar'>;
}
declare module 'expo-cli/build/commands/utils/TerminalLink.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/TerminalLink'>;
}
declare module 'expo-cli/build/commands/utils/url.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/utils/url'>;
}
declare module 'expo-cli/build/commands/webhooks.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/webhooks'>;
}
declare module 'expo-cli/build/commands/whoami.js' {
  declare module.exports: $Exports<'expo-cli/build/commands/whoami'>;
}
declare module 'expo-cli/build/commonOptions.js' {
  declare module.exports: $Exports<'expo-cli/build/commonOptions'>;
}
declare module 'expo-cli/build/credentials/actions/list.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/actions/list'>;
}
declare module 'expo-cli/build/credentials/actions/promptForCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/actions/promptForCredentials'>;
}
declare module 'expo-cli/build/credentials/api/AndroidApi.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/api/AndroidApi'>;
}
declare module 'expo-cli/build/credentials/api/AndroidApiV2Wrapper.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/api/AndroidApiV2Wrapper'>;
}
declare module 'expo-cli/build/credentials/api/IosApi.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/api/IosApi'>;
}
declare module 'expo-cli/build/credentials/api/IosApiV2Wrapper.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/api/IosApiV2Wrapper'>;
}
declare module 'expo-cli/build/credentials/context.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/context'>;
}
declare module 'expo-cli/build/credentials/credentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/credentials'>;
}
declare module 'expo-cli/build/credentials/credentialsJson/read.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/credentialsJson/read'>;
}
declare module 'expo-cli/build/credentials/credentialsJson/update.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/credentialsJson/update'>;
}
declare module 'expo-cli/build/credentials/index' {
  declare module.exports: $Exports<'expo-cli/build/credentials'>;
}
declare module 'expo-cli/build/credentials/index.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials'>;
}
declare module 'expo-cli/build/credentials/provider/AndroidCredentialsProvider.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/provider/AndroidCredentialsProvider'>;
}
declare module 'expo-cli/build/credentials/provider/index' {
  declare module.exports: $Exports<'expo-cli/build/credentials/provider'>;
}
declare module 'expo-cli/build/credentials/provider/index.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/provider'>;
}
declare module 'expo-cli/build/credentials/provider/iOSCredentialsProvider.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/provider/iOSCredentialsProvider'>;
}
declare module 'expo-cli/build/credentials/provider/provider.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/provider/provider'>;
}
declare module 'expo-cli/build/credentials/route.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/route'>;
}
declare module 'expo-cli/build/credentials/test-fixtures/mock-base64-data.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/test-fixtures/mock-base64-data'>;
}
declare module 'expo-cli/build/credentials/test-fixtures/mocks-android.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/test-fixtures/mocks-android'>;
}
declare module 'expo-cli/build/credentials/test-fixtures/mocks-constants.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/test-fixtures/mocks-constants'>;
}
declare module 'expo-cli/build/credentials/test-fixtures/mocks-context.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/test-fixtures/mocks-context'>;
}
declare module 'expo-cli/build/credentials/test-fixtures/mocks-ios.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/test-fixtures/mocks-ios'>;
}
declare module 'expo-cli/build/credentials/utils/provisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/utils/provisioningProfile'>;
}
declare module 'expo-cli/build/credentials/views/AndroidCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/AndroidCredentials'>;
}
declare module 'expo-cli/build/credentials/views/AndroidKeystore.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/AndroidKeystore'>;
}
declare module 'expo-cli/build/credentials/views/AndroidPushCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/AndroidPushCredentials'>;
}
declare module 'expo-cli/build/credentials/views/IosAppCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosAppCredentials'>;
}
declare module 'expo-cli/build/credentials/views/IosDistCert.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosDistCert'>;
}
declare module 'expo-cli/build/credentials/views/IosProvisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosProvisioningProfile'>;
}
declare module 'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosProvisioningProfileAdhoc'>;
}
declare module 'expo-cli/build/credentials/views/IosPushCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/IosPushCredentials'>;
}
declare module 'expo-cli/build/credentials/views/Select.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/Select'>;
}
declare module 'expo-cli/build/credentials/views/SetupAndroidKeystore.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupAndroidKeystore'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosBuildCredentials.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosBuildCredentials'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosDist.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosDist'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosProvisioningProfile.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosProvisioningProfile'>;
}
declare module 'expo-cli/build/credentials/views/SetupIosPush.js' {
  declare module.exports: $Exports<'expo-cli/build/credentials/views/SetupIosPush'>;
}
declare module 'expo-cli/build/easJson.js' {
  declare module.exports: $Exports<'expo-cli/build/easJson'>;
}
declare module 'expo-cli/build/exit.js' {
  declare module.exports: $Exports<'expo-cli/build/exit'>;
}
declare module 'expo-cli/build/exp.js' {
  declare module.exports: $Exports<'expo-cli/build/exp'>;
}
declare module 'expo-cli/build/git.js' {
  declare module.exports: $Exports<'expo-cli/build/git'>;
}
declare module 'expo-cli/build/log.js' {
  declare module.exports: $Exports<'expo-cli/build/log'>;
}
declare module 'expo-cli/build/printRunInstructionsAsync.js' {
  declare module.exports: $Exports<'expo-cli/build/printRunInstructionsAsync'>;
}
declare module 'expo-cli/build/projects.js' {
  declare module.exports: $Exports<'expo-cli/build/projects'>;
}
declare module 'expo-cli/build/prompt.js' {
  declare module.exports: $Exports<'expo-cli/build/prompt'>;
}
declare module 'expo-cli/build/prompts.js' {
  declare module.exports: $Exports<'expo-cli/build/prompts'>;
}
declare module 'expo-cli/build/sendTo.js' {
  declare module.exports: $Exports<'expo-cli/build/sendTo'>;
}
declare module 'expo-cli/build/update.js' {
  declare module.exports: $Exports<'expo-cli/build/update'>;
}
declare module 'expo-cli/build/uploads.js' {
  declare module.exports: $Exports<'expo-cli/build/uploads'>;
}
declare module 'expo-cli/build/urlOpts.js' {
  declare module.exports: $Exports<'expo-cli/build/urlOpts'>;
}
declare module 'expo-cli/build/validators.js' {
  declare module.exports: $Exports<'expo-cli/build/validators'>;
}
