// flow-typed signature: 9636d1b56ec4ffb7417d16d0e1f6092b
// flow-typed version: <<STUB>>/firebase_v7.9.0/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/analytics/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/analytics/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/app/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/app/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/auth/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/auth/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/database/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/database/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/dist/index.node.cjs' {
  declare module.exports: any;
}

declare module 'firebase/dist/index.rn.cjs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-client-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-error-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-firestore-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-messaging-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-storage-externs' {
  declare module.exports: any;
}

declare module 'firebase/firebase-analytics' {
  declare module.exports: any;
}

declare module 'firebase/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase/firebase-firestore' {
  declare module.exports: any;
}

declare module 'firebase/firebase-functions' {
  declare module.exports: any;
}

declare module 'firebase/firebase-installations' {
  declare module.exports: any;
}

declare module 'firebase/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase/firebase-performance-standalone.es2017' {
  declare module.exports: any;
}

declare module 'firebase/firebase-performance-standalone' {
  declare module.exports: any;
}

declare module 'firebase/firebase-performance' {
  declare module.exports: any;
}

declare module 'firebase/firebase-remote-config' {
  declare module.exports: any;
}

declare module 'firebase/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase/firebase' {
  declare module.exports: any;
}

declare module 'firebase/firestore/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/firestore/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/functions/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/functions/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/installations/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/installations/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/messaging/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/messaging/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/performance/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/performance/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/remote-config/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/remote-config/dist/index.esm' {
  declare module.exports: any;
}

declare module 'firebase/storage/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/storage/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/analytics/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/analytics/dist/index.cjs'>;
}
declare module 'firebase/analytics/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/analytics/dist/index.esm'>;
}
declare module 'firebase/app/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/app/dist/index.cjs'>;
}
declare module 'firebase/app/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/app/dist/index.esm'>;
}
declare module 'firebase/auth/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/auth/dist/index.cjs'>;
}
declare module 'firebase/auth/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/auth/dist/index.esm'>;
}
declare module 'firebase/database/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/database/dist/index.cjs'>;
}
declare module 'firebase/database/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/database/dist/index.esm'>;
}
declare module 'firebase/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/dist/index.cjs'>;
}
declare module 'firebase/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/dist/index.esm'>;
}
declare module 'firebase/dist/index.node.cjs.js' {
  declare module.exports: $Exports<'firebase/dist/index.node.cjs'>;
}
declare module 'firebase/dist/index.rn.cjs.js' {
  declare module.exports: $Exports<'firebase/dist/index.rn.cjs'>;
}
declare module 'firebase/externs/firebase-app-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-externs'>;
}
declare module 'firebase/externs/firebase-app-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-internal-externs'>;
}
declare module 'firebase/externs/firebase-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-auth-externs'>;
}
declare module 'firebase/externs/firebase-client-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-client-auth-externs'>;
}
declare module 'firebase/externs/firebase-database-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-externs'>;
}
declare module 'firebase/externs/firebase-database-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-internal-externs'>;
}
declare module 'firebase/externs/firebase-error-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-error-externs'>;
}
declare module 'firebase/externs/firebase-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-externs'>;
}
declare module 'firebase/externs/firebase-firestore-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-firestore-externs'>;
}
declare module 'firebase/externs/firebase-messaging-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-messaging-externs'>;
}
declare module 'firebase/externs/firebase-storage-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-storage-externs'>;
}
declare module 'firebase/firebase-analytics.js' {
  declare module.exports: $Exports<'firebase/firebase-analytics'>;
}
declare module 'firebase/firebase-app.js' {
  declare module.exports: $Exports<'firebase/firebase-app'>;
}
declare module 'firebase/firebase-auth.js' {
  declare module.exports: $Exports<'firebase/firebase-auth'>;
}
declare module 'firebase/firebase-database.js' {
  declare module.exports: $Exports<'firebase/firebase-database'>;
}
declare module 'firebase/firebase-firestore.js' {
  declare module.exports: $Exports<'firebase/firebase-firestore'>;
}
declare module 'firebase/firebase-functions.js' {
  declare module.exports: $Exports<'firebase/firebase-functions'>;
}
declare module 'firebase/firebase-installations.js' {
  declare module.exports: $Exports<'firebase/firebase-installations'>;
}
declare module 'firebase/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase/firebase-messaging'>;
}
declare module 'firebase/firebase-performance-standalone.es2017.js' {
  declare module.exports: $Exports<'firebase/firebase-performance-standalone.es2017'>;
}
declare module 'firebase/firebase-performance-standalone.js' {
  declare module.exports: $Exports<'firebase/firebase-performance-standalone'>;
}
declare module 'firebase/firebase-performance.js' {
  declare module.exports: $Exports<'firebase/firebase-performance'>;
}
declare module 'firebase/firebase-remote-config.js' {
  declare module.exports: $Exports<'firebase/firebase-remote-config'>;
}
declare module 'firebase/firebase-storage.js' {
  declare module.exports: $Exports<'firebase/firebase-storage'>;
}
declare module 'firebase/firebase.js' {
  declare module.exports: $Exports<'firebase/firebase'>;
}
declare module 'firebase/firestore/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/firestore/dist/index.cjs'>;
}
declare module 'firebase/firestore/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/firestore/dist/index.esm'>;
}
declare module 'firebase/functions/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/functions/dist/index.cjs'>;
}
declare module 'firebase/functions/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/functions/dist/index.esm'>;
}
declare module 'firebase/installations/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/installations/dist/index.cjs'>;
}
declare module 'firebase/installations/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/installations/dist/index.esm'>;
}
declare module 'firebase/messaging/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/messaging/dist/index.cjs'>;
}
declare module 'firebase/messaging/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/messaging/dist/index.esm'>;
}
declare module 'firebase/performance/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/performance/dist/index.cjs'>;
}
declare module 'firebase/performance/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/performance/dist/index.esm'>;
}
declare module 'firebase/remote-config/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/remote-config/dist/index.cjs'>;
}
declare module 'firebase/remote-config/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/remote-config/dist/index.esm'>;
}
declare module 'firebase/storage/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/storage/dist/index.cjs'>;
}
declare module 'firebase/storage/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/storage/dist/index.esm'>;
}
