// flow-typed signature: cca5f60a588c9f967baa2fc60315c39f
// flow-typed version: <<STUB>>/npm-license-crawler_v0.2.1/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-license-crawler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-license-crawler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-license-crawler/examples/api-example' {
  declare module.exports: any;
}

declare module 'npm-license-crawler/lib/directoryreader' {
  declare module.exports: any;
}

declare module 'npm-license-crawler/lib' {
  declare module.exports: any;
}

declare module 'npm-license-crawler/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-license-crawler/examples/api-example.js' {
  declare module.exports: $Exports<'npm-license-crawler/examples/api-example'>;
}
declare module 'npm-license-crawler/lib/directoryreader.js' {
  declare module.exports: $Exports<'npm-license-crawler/lib/directoryreader'>;
}
declare module 'npm-license-crawler/lib/index' {
  declare module.exports: $Exports<'npm-license-crawler/lib'>;
}
declare module 'npm-license-crawler/lib/index.js' {
  declare module.exports: $Exports<'npm-license-crawler/lib'>;
}
declare module 'npm-license-crawler/test/test.js' {
  declare module.exports: $Exports<'npm-license-crawler/test/test'>;
}
