// flow-typed signature: ba7e5ac5c0e64749c275e6a430a8e606
// flow-typed version: <<STUB>>/sentry-expo_v3.0.2/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sentry-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sentry-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sentry-expo/dist/hooks/upload-sourcemaps' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/integrations/bare' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/integrations/managed' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/sentry.expo' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/sentry' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/sentry.web' {
  declare module.exports: any;
}

declare module 'sentry-expo/dist/utils' {
  declare module.exports: any;
}

declare module 'sentry-expo/upload-sourcemaps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sentry-expo/dist/hooks/upload-sourcemaps.js' {
  declare module.exports: $Exports<'sentry-expo/dist/hooks/upload-sourcemaps'>;
}
declare module 'sentry-expo/dist/index' {
  declare module.exports: $Exports<'sentry-expo/dist'>;
}
declare module 'sentry-expo/dist/index.js' {
  declare module.exports: $Exports<'sentry-expo/dist'>;
}
declare module 'sentry-expo/dist/integrations/bare.js' {
  declare module.exports: $Exports<'sentry-expo/dist/integrations/bare'>;
}
declare module 'sentry-expo/dist/integrations/managed.js' {
  declare module.exports: $Exports<'sentry-expo/dist/integrations/managed'>;
}
declare module 'sentry-expo/dist/sentry.expo.js' {
  declare module.exports: $Exports<'sentry-expo/dist/sentry.expo'>;
}
declare module 'sentry-expo/dist/sentry.js' {
  declare module.exports: $Exports<'sentry-expo/dist/sentry'>;
}
declare module 'sentry-expo/dist/sentry.web.js' {
  declare module.exports: $Exports<'sentry-expo/dist/sentry.web'>;
}
declare module 'sentry-expo/dist/utils.js' {
  declare module.exports: $Exports<'sentry-expo/dist/utils'>;
}
declare module 'sentry-expo/upload-sourcemaps.js' {
  declare module.exports: $Exports<'sentry-expo/upload-sourcemaps'>;
}
